[#status]
image:https://maven-badges.herokuapp.com/maven-central/com.github.funthomas424242/rades-example.template/badge.svg?style=flat["Maven Central", link="https://maven-badges.herokuapp.com/maven-central/com.github.funthomas424242/rades-example.template"]
// image:https://api.bintray.com/packages/funthomas424242/funthomas424242-libs/rades-example.template/images/download.svg[link="https://bintray.com/funthomas424242/funthomas424242-libs/rades-example.template/_latestVersion"]
image:https://travis-ci.org/FunThomas424242/rades-example.template.svg?branch=master["Build Status", link="https://travis-ci.org/FunThomas424242/rades-example.template"]
image:https://api.codacy.com/project/badge/Grade/88bf76546176437ea389629a2087d1b5["Codacy code quality", link="https://www.codacy.com/app/FunThomas424242/rades-example.template?utm_source=github.com&utm_medium=referral&utm_content=FunThomas424242/rades-example.template&utm_campaign=Badge_Grade"]
image:https://codecov.io/gh/FunThomas424242/rades-example.template/branch/master/graph/badge.svg[link="https://codecov.io/gh/FunThomas424242/rades-example.template"]
image:http://images.webestools.com/buttons.php?frm=2&btn_type=11&txt=Scrum Board["Scrum Board,scaledwidth="15%"", link="https://github.com/FunThomas424242/rades-example.template/projects/1"]

image:https://img.shields.io/badge/readme%20style-standard-brightgreen.svg?style=flat-square["standard-readme compilant",link="https://github.com/RichardLitt/standard-readme"]

== rades-example.template
Template zum Aufsetzen eines RADES Beispiel Projektes.




Das README File ist für gewöhnlich der erste Kontakt mit Deinem Kode. Es sollte den Leuten erzählen warum sie Dein Modul nutzen sollen, wie sie es installieren können und wie sie es nutzen können. Ein Standard wie Dein README file zu schreiben ist, erleichtert dessen Erstellung und Wartung. Die Erstellung einer guten Dokumentation ist harte Arbeit. 



This repository contains:

1. [The specification](spec.md) for how a standard README should look.
2. A link to a linter you can use to keep your README maintained ([work in progress](https://github.com/RichardLitt/standard-readme/issues/5)).
3. A link to [a generator](https://github.com/RichardLitt/generator-standard-readme) you can use to create standard READMEs.
4. [A badge](#badge) to point to this spec.
5. [Examples of standard READMEs](example-readmes/) - such as this file you are reading.

Standard Readme is designed for open source libraries. Although it’s [historically](#background) made for Node and npm projects, it also applies to libraries in other languages and package managers.


== Inhaltsverzeichnis

- [#hintergrund] Hintergrund
- [Install](#install)
- [Usage](#usage)
	- [Generator](#generator)
- [Badge](#badge)
- [Example Readmes](#example-readmes)
- [Related Efforts](#related-efforts)
- [Maintainers](#maintainers)
- [Contributing](#contributing)
- [License](#license)

[hintergrund]
== Hintergrund
Lange habe ich versucht ein Projekttemplate zu erstellen. Es gibt dazu bereits einige Projekte in meinem persönlichem Account. Doch nun ist mir Github dankenswerter Weise zuvor gekommen und hat einen Mechanismus angeboten ein bestehendes Projekt als Template Projekt zu markieren. Das konnte ich prima nutzen und möchte mich dafür recht herzlich Bedanken. 
Dieses Projekt stellt ein Template für alle Projekte im RADES Beispiel Projekt Style dar. Wem es gefällt oder wer ein RADES Beispiel Projekt beisteuern möchte, der darf es gerne nutzen - alle anderen natürlich auch ;)

== Installation

Installation bedeutet im konkreten Fall Erstellung eines neuen Repositories in Deinem Account mit exakt der selben Verzeichnis- und Dateistruktur wie sie dieses Projekt hier aufweist.

== Nutzung

Das Projekt ist ein Template für Projekte im Style von RADES Beispielen. Wem die Projektstruktur gefällt der klickt einfach auf den Template Button im oberen Bildschirmbereich.

== Literatur und Quellen im Netz

* https://github.com/noffle/art-of-readme[Art of Readme] - Erlerne die Kunst gute READMEs zu schreiben.
* https://github.com/davidbgk/open-source-template/[open-source-template] - A README template to encourage open-source contributions.
* https://www.makeareadme.com/
* https://github.com/RichardLitt/standard-readme
* https://github.com/RichardLitt/generator-standard-readme/
* https://github.com/noffle/art-of-readme



== Projekteigner

https://github.com/FunThomas424242[@Huluvu424242]

== Unterstützung

Unterstützung ist jederzeit erwünscht. Ein gelungener Einstieg sollte sich über Duchlesen, Prüfen/Testen, Korrigieren/Weiterentwickeln und Änderungen als Pull-Request einstellen, ergeben.
Du kannst aber auch jederzeit gern ein Ticket öffnen unter: https://github.com/PIUGroup/rades-example.template/issues/new/choose[Ticket Erstellen].

Dieses Projekt folgt den unter https://www.contributor-covenant.org/de/version/1/4/code-of-conduct/[Verhaltenskodex für Unterstützer] veröffentlichten Verhaltensregeln.

=== Unterstützer

Dieses Projekt lebt vom Support all seiner Unterstützer genau wie auch vom Support all jener welche nicht namentlich bekannt sind aber das Projekt im Internet bekannt machen oder anderweitig unterstützen.

Vielen Dank für all Euren Suppprt! 

////
Ab 100 Sterne auf github ist eine Verwaltung über opencollective für OpenSource Projekte möglich
This project exists thanks to all the people who contribute. 
<a href="graphs/contributors"><img src="https://opencollective.com/standard-readme/contributors.svg?width=890&button=false" /></a>
////



== Lizenz

.LICENSE[LGPL-3.0 ff.] © PIUG


